### ISSUE TITLE
Interface class (setBlock / batching)

### ISSUE THREAD

**Issue by Flashing-Blinkenlights** [nilsgawlik/gdmc_http_client_python#3]
**Feature branch: `setblock-batching`**

The setblock and batch block placement commands have many similarity and it might make sense to combine them under the Interface class.

### Suggested implementation:

```py
class Interface():
  self.bufferMode = False
  self.bufferLimit = 100
  self.buffer = []

[...]

def setBlock(x, y, z, block):
  if self.bufferMode:
    [buffered setBlock]
  else:
    [regular setBlock]
```

Pro:
- Convenient switching (e.g. for debugging purposes)
- Transparent implementation

Con:
- [fill me]

**Comment by nilsgawlik** [comment]
Makes sense if it's combined with the Interface class.

I haven't looked at the interface pull request yet (#12) , but maybe we could just think of this issue as the 'interface class issue'.

There is one problem that I'm not sure you've considered, which is that at the end of the program the blocks remaining in the buffer always need to be sent. This is something that's hard to have abstracted away, so there still might need to be an `Interface.finalize()` or `Interface.sendRemainingBlocks()` function

**Comment by nilsgawlik** [comment]
I did some extra implementation in the pull request (#12), I hope this is ok. It still feels a little bit rough around the edges to me, though. 

And I'm not convinced that some functions such as requestBuildArea or runCommand should be inside the interface class, rather than just being independent interface functions (since they map very directly to interface endpoints).

On a related note, I'm not super sure about the TODOs in the runCommand function concerning executing commands in relative coordinates. I think they would require server-side work so that the position/rotation of the command source can actually be set.
